persandstrom/python-verisure

.gitignore
verisure/__init__.py
verisure/devices/alarm.py
verisure/session.py

I hope this is a valid contribution to the project:
* Adds some more Error types and handles error when getting HTML instead of JSON from Verisure.
* Fixes some problem with wait_while_pending
* Fixes issue #4 
There's probably room for improvements in my code, I'm quite new to python

Better error handling when communicating with MyPages

---

setup.py
verisure/devices/smartplug.py

Wait while updating function for smartplugs

Smartplug wait while updating

---

.travis.yml
requirements.txt
setup.py
verisure/session.py

Due to an encoding error when parsing html I have decided to use existing packages to handle the parsing rather then using regex.

Use beautifulsoup4 and json modules

---

setup.py
verisure.py
verisure/devices/smartplug.py
verisure/session.py

Makes it possible to det smartplug details and set smartplug location
two new functions:
get_details(device_id)
and 
set_location(device_id, location)

Set smartplug location

---

setup.py
verisure/devices/lock.py
verisure/session.py

new functions for lock
```
.get_autorelock()
```
and
```
.set_autorelock( <str> device_id, <bool> autorelock )
```
.

autorelock

---

setup.py
verisure.py
verisure/session.py

Bugfix: unicode characters was no longer unescaped

restore unescape

---

.travis.yml
README.md
requirements-dev.txt
setup.py
verisure.py
verisure/__init__.py
verisure/devices/__init__.py
verisure/devices/alarm.py
verisure/devices/lock.py
verisure/devices/smartplug.py
verisure/session.py

Beautifulsoup was not trivial to use with python 2.6

Remove beautifulsoup

---

verisure/devices/lock.py

Added the wait_while_pending for the lock.
It uses the excact same method as the alarm by using checkstate.cmd to refresh.

Add wait_while_pending for lock

---

verisure/session.py

Hi, I noticed that I didn't get the correct error type and I think this will fix it.

Some error in the error handling

---

setup.py
verisure/session.py

Don't let the module raise requests exceptions

Exceptions

---

setup.py
verisure/devices/ethernet.py

The ethernet information on MyPages has changed from a list of components to a single component

The data about ethernet component has changed on MyPages

---

README.md
setup.py
verisure.py
verisure/devices/alarm.py
verisure/devices/climate.py
verisure/devices/lock.py
verisure/session.py

New function: Get climate history
usage
```
verisure.climate.get_history('1A2B 3C4D')
```
or
```
python verisure.py user@example.com mypassword history climate '5AC2 4LXH'
```

climate history

---

setup.py
verisure/devices/eventlog.py

Details should be printed correctly and device location name is separated from device type

eventlog details fix

---

setup.py
verisure/devices/ethernet.py
verisure/devices/eventlog.py

Will fix eventlog for smartlock

Fix eventlog lock

---

setup.py
verisure/session.py

longer timeout

---

.travis.yml
README.md
setup.py
verisure/__main__.py
verisure/mypages.py
verisure/session.py

Add option to select which installation to query

Add installation numer

---

verisure/devices/smartcam.py
verisure/session.py

WIP, Adding capture functionallity from mypages. Capture is now working.
usage:
import verisure
mypages = verisure.MyPages('username', 'password')
mypages.login()
mypages.smartcam.capture('device_serial_number') -> captures a new image to mypages.
mypages.smartcam.get_image_list() -> get a list of image names to use for downloading.
mypages.smartcam.download_image('device_id', 'image_name', destination_path) -> Download the specifyed image to destination_path.
Any other things that might be good?

Smartcam capture function

---

verisure/devices/smartcam.py

Return a dict with image_id as key and device_id as value.
Usecase is to accsess the device_id of the cam from applications.

Return a dict of image_id and device_id instead of just image_id

---

verisure/session.py

I have tested the lock implementation, #48 , and had to make some changes to the session.py and now it's working as expected. I will make a more thorough code review tomorrow.

Fixed some bugs in the Lock implementation

---

README.md
setup.py
verisure/__main__.py
verisure/session.py

New function to read vacation mode

vacation mode support

---

verisure/__main__.py
verisure/session.py

Add the ability to fetch the door/window contacts statuses.

Add door_window status page fetching

---

README.md
setup.py
verisure/__main__.py
verisure/session.py

Add LOCK and UNLOCK as filter options for event log

eventlog lock filter options

---

README.md
setup.py
verisure/__main__.py
verisure/session.py
verisure/urls.py

Automatically switch between e-api01.verisure.com and e-api02.verisure.com

switch sub domains

---

verisure/__main__.py
verisure/session.py

Add with support for session

---

verisure/session.py
verisure/urls.py

Added support for Panasonic HeatPumps, tested with PANASONIC_NE_9_PKE_1

Added support for Panasonic HeatPumps

---

verisure/session.py

See https://github.com/persandstrom/python-verisure/issues/112

Issue-112: replacing "notificationCategories" by "eventCategories"

---

README.md
setup.py
verisure/session.py

Resonse error was loaded as json, but not formatted as json, fixed

response error text should not be loaded as json

---

README.md
requirements.txt
setup.py
verisure/session.py

New authentication server. Use pickle for cookie

Automation login

---

README.md
setup.py
verisure/session.py

Fix content type
